require("dotenv").config();
const pool = require("./connect");

const countries = [
  { name: "Afghanistan", continent: "Asia", iso_code: "AF", flag_url: "https://flagcdn.com/af.svg" },
  { name: "Albania", continent: "Europe", iso_code: "AL", flag_url: "https://flagcdn.com/al.svg" },
  { name: "Algeria", continent: "Africa", iso_code: "DZ", flag_url: "https://flagcdn.com/dz.svg" },
  { name: "Andorra", continent: "Europe", iso_code: "AD", flag_url: "https://flagcdn.com/ad.svg" },
  { name: "Angola", continent: "Africa", iso_code: "AO", flag_url: "https://flagcdn.com/ao.svg" },
  { name: "Antigua and Barbuda", continent: "North America", iso_code: "AG", flag_url: "https://flagcdn.com/ag.svg" },
  { name: "Argentina", continent: "South America", iso_code: "AR", flag_url: "https://flagcdn.com/ar.svg" },
  { name: "Armenia", continent: "Asia", iso_code: "AM", flag_url: "https://flagcdn.com/am.svg" },
  { name: "Australia", continent: "Oceania", iso_code: "AU", flag_url: "https://flagcdn.com/au.svg" },
  { name: "Austria", continent: "Europe", iso_code: "AT", flag_url: "https://flagcdn.com/at.svg" },
  { name: "Azerbaijan", continent: "Asia", iso_code: "AZ", flag_url: "https://flagcdn.com/az.svg" },
  { name: "Bahamas", continent: "North America", iso_code: "BS", flag_url: "https://flagcdn.com/bs.svg" },
  { name: "Bahrain", continent: "Asia", iso_code: "BH", flag_url: "https://flagcdn.com/bh.svg" },
  { name: "Bangladesh", continent: "Asia", iso_code: "BD", flag_url: "https://flagcdn.com/bd.svg" },
  { name: "Barbados", continent: "North America", iso_code: "BB", flag_url: "https://flagcdn.com/bb.svg" },
  { name: "Belarus", continent: "Europe", iso_code: "BY", flag_url: "https://flagcdn.com/by.svg" },
  { name: "Belgium", continent: "Europe", iso_code: "BE", flag_url: "https://flagcdn.com/be.svg" },
  { name: "Belize", continent: "North America", iso_code: "BZ", flag_url: "https://flagcdn.com/bz.svg" },
  { name: "Benin", continent: "Africa", iso_code: "BJ", flag_url: "https://flagcdn.com/bj.svg" },
  { name: "Bhutan", continent: "Asia", iso_code: "BT", flag_url: "https://flagcdn.com/bt.svg" },
  { name: "Bolivia", continent: "South America", iso_code: "BO", flag_url: "https://flagcdn.com/bo.svg" },
  { name: "Bosnia and Herzegovina", continent: "Europe", iso_code: "BA", flag_url: "https://flagcdn.com/ba.svg" },
  { name: "Botswana", continent: "Africa", iso_code: "BW", flag_url: "https://flagcdn.com/bw.svg" },
  { name: "Brazil", continent: "South America", iso_code: "BR", flag_url: "https://flagcdn.com/br.svg" },
  { name: "Brunei", continent: "Asia", iso_code: "BN", flag_url: "https://flagcdn.com/bn.svg" },
  { name: "Bulgaria", continent: "Europe", iso_code: "BG", flag_url: "https://flagcdn.com/bg.svg" },
  { name: "Burkina Faso", continent: "Africa", iso_code: "BF", flag_url: "https://flagcdn.com/bf.svg" },
  { name: "Burundi", continent: "Africa", iso_code: "BI", flag_url: "https://flagcdn.com/bi.svg" },
  { name: "Cabo Verde", continent: "Africa", iso_code: "CV", flag_url: "https://flagcdn.com/cv.svg" },
  { name: "Cambodia", continent: "Asia", iso_code: "KH", flag_url: "https://flagcdn.com/kh.svg" },
  { name: "Cameroon", continent: "Africa", iso_code: "CM", flag_url: "https://flagcdn.com/cm.svg" },
  { name: "Canada", continent: "North America", iso_code: "CA", flag_url: "https://flagcdn.com/ca.svg" },
  { name: "Central African Republic", continent: "Africa", iso_code: "CF", flag_url: "https://flagcdn.com/cf.svg" },
  { name: "Chad", continent: "Africa", iso_code: "TD", flag_url: "https://flagcdn.com/td.svg" },
  { name: "Chile", continent: "South America", iso_code: "CL", flag_url: "https://flagcdn.com/cl.svg" },
  { name: "China", continent: "Asia", iso_code: "CN", flag_url: "https://flagcdn.com/cn.svg" },
  { name: "Colombia", continent: "South America", iso_code: "CO", flag_url: "https://flagcdn.com/co.svg" },
  { name: "Comoros", continent: "Africa", iso_code: "KM", flag_url: "https://flagcdn.com/km.svg" },
  { name: "Congo", continent: "Africa", iso_code: "CG", flag_url: "https://flagcdn.com/cg.svg" },
  { name: "Costa Rica", continent: "North America", iso_code: "CR", flag_url: "https://flagcdn.com/cr.svg" },
  { name: "Croatia", continent: "Europe", iso_code: "HR", flag_url: "https://flagcdn.com/hr.svg" },
  { name: "Cuba", continent: "North America", iso_code: "CU", flag_url: "https://flagcdn.com/cu.svg" },
  { name: "Cyprus", continent: "Europe", iso_code: "CY", flag_url: "https://flagcdn.com/cy.svg" },
  { name: "Czech Republic", continent: "Europe", iso_code: "CZ", flag_url: "https://flagcdn.com/cz.svg" },
  { name: "Democratic Republic of the Congo", continent: "Africa", iso_code: "CD", flag_url: "https://flagcdn.com/cd.svg" },
  { name: "Denmark", continent: "Europe", iso_code: "DK", flag_url: "https://flagcdn.com/dk.svg" },
  { name: "Djibouti", continent: "Africa", iso_code: "DJ", flag_url: "https://flagcdn.com/dj.svg" },
  { name: "Dominica", continent: "North America", iso_code: "DM", flag_url: "https://flagcdn.com/dm.svg" },
  { name: "Dominican Republic", continent: "North America", iso_code: "DO", flag_url: "https://flagcdn.com/do.svg" },
  { name: "Ecuador", continent: "South America", iso_code: "EC", flag_url: "https://flagcdn.com/ec.svg" },
  { name: "Egypt", continent: "Africa", iso_code: "EG", flag_url: "https://flagcdn.com/eg.svg" },
  { name: "El Salvador", continent: "North America", iso_code: "SV", flag_url: "https://flagcdn.com/sv.svg" },
  { name: "Equatorial Guinea", continent: "Africa", iso_code: "GQ", flag_url: "https://flagcdn.com/gq.svg" },
  { name: "Eritrea", continent: "Africa", iso_code: "ER", flag_url: "https://flagcdn.com/er.svg" },
  { name: "Estonia", continent: "Europe", iso_code: "EE", flag_url: "https://flagcdn.com/ee.svg" },
  { name: "Eswatini", continent: "Africa", iso_code: "SZ", flag_url: "https://flagcdn.com/sz.svg" },
  { name: "Ethiopia", continent: "Africa", iso_code: "ET", flag_url: "https://flagcdn.com/et.svg" },
  { name: "Fiji", continent: "Oceania", iso_code: "FJ", flag_url: "https://flagcdn.com/fj.svg" },
  { name: "Finland", continent: "Europe", iso_code: "FI", flag_url: "https://flagcdn.com/fi.svg" },
  { name: "France", continent: "Europe", iso_code: "FR", flag_url: "https://flagcdn.com/fr.svg" },
  { name: "Gabon", continent: "Africa", iso_code: "GA", flag_url: "https://flagcdn.com/ga.svg" },
  { name: "Gambia", continent: "Africa", iso_code: "GM", flag_url: "https://flagcdn.com/gm.svg" },
  { name: "Georgia", continent: "Asia", iso_code: "GE", flag_url: "https://flagcdn.com/ge.svg" },
  { name: "Germany", continent: "Europe", iso_code: "DE", flag_url: "https://flagcdn.com/de.svg" },
  { name: "Ghana", continent: "Africa", iso_code: "GH", flag_url: "https://flagcdn.com/gh.svg" },
  { name: "Greece", continent: "Europe", iso_code: "GR", flag_url: "https://flagcdn.com/gr.svg" },
  { name: "Grenada", continent: "North America", iso_code: "GD", flag_url: "https://flagcdn.com/gd.svg" },
  { name: "Guatemala", continent: "North America", iso_code: "GT", flag_url: "https://flagcdn.com/gt.svg" },
  { name: "Guinea", continent: "Africa", iso_code: "GN", flag_url: "https://flagcdn.com/gn.svg" },
  { name: "Guinea-Bissau", continent: "Africa", iso_code: "GW", flag_url: "https://flagcdn.com/gw.svg" },
  { name: "Guyana", continent: "South America", iso_code: "GY", flag_url: "https://flagcdn.com/gy.svg" },
  { name: "Haiti", continent: "North America", iso_code: "HT", flag_url: "https://flagcdn.com/ht.svg" },
  { name: "Honduras", continent: "North America", iso_code: "HN", flag_url: "https://flagcdn.com/hn.svg" },
  { name: "Hungary", continent: "Europe", iso_code: "HU", flag_url: "https://flagcdn.com/hu.svg" },
  { name: "Iceland", continent: "Europe", iso_code: "IS", flag_url: "https://flagcdn.com/is.svg" },
  { name: "India", continent: "Asia", iso_code: "IN", flag_url: "https://flagcdn.com/in.svg" },
  { name: "Indonesia", continent: "Asia", iso_code: "ID", flag_url: "https://flagcdn.com/id.svg" },
  { name: "Iran", continent: "Asia", iso_code: "IR", flag_url: "https://flagcdn.com/ir.svg" },
  { name: "Iraq", continent: "Asia", iso_code: "IQ", flag_url: "https://flagcdn.com/iq.svg" },
  { name: "Ireland", continent: "Europe", iso_code: "IE", flag_url: "https://flagcdn.com/ie.svg" },
  { name: "Israel", continent: "Asia", iso_code: "IL", flag_url: "https://flagcdn.com/il.svg" },
  { name: "Italy", continent: "Europe", iso_code: "IT", flag_url: "https://flagcdn.com/it.svg" },
  { name: "Jamaica", continent: "North America", iso_code: "JM", flag_url: "https://flagcdn.com/jm.svg" },
  { name: "Japan", continent: "Asia", iso_code: "JP", flag_url: "https://flagcdn.com/jp.svg" },
  { name: "Jordan", continent: "Asia", iso_code: "JO", flag_url: "https://flagcdn.com/jo.svg" },
  { name: "Kazakhstan", continent: "Asia", iso_code: "KZ", flag_url: "https://flagcdn.com/kz.svg" },
  { name: "Kenya", continent: "Africa", iso_code: "KE", flag_url: "https://flagcdn.com/ke.svg" },
  { name: "Kiribati", continent: "Oceania", iso_code: "KI", flag_url: "https://flagcdn.com/ki.svg" },
  { name: "Kuwait", continent: "Asia", iso_code: "KW", flag_url: "https://flagcdn.com/kw.svg" },
  { name: "Kyrgyzstan", continent: "Asia", iso_code: "KG", flag_url: "https://flagcdn.com/kg.svg" },
  { name: "Laos", continent: "Asia", iso_code: "LA", flag_url: "https://flagcdn.com/la.svg" },
  { name: "Latvia", continent: "Europe", iso_code: "LV", flag_url: "https://flagcdn.com/lv.svg" },
  { name: "Lebanon", continent: "Asia", iso_code: "LB", flag_url: "https://flagcdn.com/lb.svg" },
  { name: "Lesotho", continent: "Africa", iso_code: "LS", flag_url: "https://flagcdn.com/ls.svg" },
  { name: "Liberia", continent: "Africa", iso_code: "LR", flag_url: "https://flagcdn.com/lr.svg" },
  { name: "Libya", continent: "Africa", iso_code: "LY", flag_url: "https://flagcdn.com/ly.svg" },
  { name: "Liechtenstein", continent: "Europe", iso_code: "LI", flag_url: "https://flagcdn.com/li.svg" },
  { name: "Lithuania", continent: "Europe", iso_code: "LT", flag_url: "https://flagcdn.com/lt.svg" },
  { name: "Luxembourg", continent: "Europe", iso_code: "LU", flag_url: "https://flagcdn.com/lu.svg" },
  { name: "Madagascar", continent: "Africa", iso_code: "MG", flag_url: "https://flagcdn.com/mg.svg" },
  { name: "Malawi", continent: "Africa", iso_code: "MW", flag_url: "https://flagcdn.com/mw.svg" },
  { name: "Malaysia", continent: "Asia", iso_code: "MY", flag_url: "https://flagcdn.com/my.svg" },
  { name: "Maldives", continent: "Asia", iso_code: "MV", flag_url: "https://flagcdn.com/mv.svg" },
  { name: "Mali", continent: "Africa", iso_code: "ML", flag_url: "https://flagcdn.com/ml.svg" },
  { name: "Malta", continent: "Europe", iso_code: "MT", flag_url: "https://flagcdn.com/mt.svg" },
  { name: "Marshall Islands", continent: "Oceania", iso_code: "MH", flag_url: "https://flagcdn.com/mh.svg" },
  { name: "Mauritania", continent: "Africa", iso_code: "MR", flag_url: "https://flagcdn.com/mr.svg" },
  { name: "Mauritius", continent: "Africa", iso_code: "MU", flag_url: "https://flagcdn.com/mu.svg" },
  { name: "Mexico", continent: "North America", iso_code: "MX", flag_url: "https://flagcdn.com/mx.svg" },
  { name: "Micronesia", continent: "Oceania", iso_code: "FM", flag_url: "https://flagcdn.com/fm.svg" },
  { name: "Moldova", continent: "Europe", iso_code: "MD", flag_url: "https://flagcdn.com/md.svg" },
  { name: "Monaco", continent: "Europe", iso_code: "MC", flag_url: "https://flagcdn.com/mc.svg" },
  { name: "Mongolia", continent: "Asia", iso_code: "MN", flag_url: "https://flagcdn.com/mn.svg" },
  { name: "Montenegro", continent: "Europe", iso_code: "ME", flag_url: "https://flagcdn.com/me.svg" },
  { name: "Morocco", continent: "Africa", iso_code: "MA", flag_url: "https://flagcdn.com/ma.svg" },
  { name: "Mozambique", continent: "Africa", iso_code: "MZ", flag_url: "https://flagcdn.com/mz.svg" },
  { name: "Myanmar", continent: "Asia", iso_code: "MM", flag_url: "https://flagcdn.com/mm.svg" },
  { name: "Namibia", continent: "Africa", iso_code: "NA", flag_url: "https://flagcdn.com/na.svg" },
  { name: "Nauru", continent: "Oceania", iso_code: "NR", flag_url: "https://flagcdn.com/nr.svg" },
  { name: "Nepal", continent: "Asia", iso_code: "NP", flag_url: "https://flagcdn.com/np.svg" },
  { name: "Netherlands", continent: "Europe", iso_code: "NL", flag_url: "https://flagcdn.com/nl.svg" },
  { name: "New Zealand", continent: "Oceania", iso_code: "NZ", flag_url: "https://flagcdn.com/nz.svg" },
  { name: "Nicaragua", continent: "North America", iso_code: "NI", flag_url: "https://flagcdn.com/ni.svg" },
  { name: "Niger", continent: "Africa", iso_code: "NE", flag_url: "https://flagcdn.com/ne.svg" },
  { name: "Nigeria", continent: "Africa", iso_code: "NG", flag_url: "https://flagcdn.com/ng.svg" },
  { name: "North Korea", continent: "Asia", iso_code: "KP", flag_url: "https://flagcdn.com/kp.svg" },
  { name: "North Macedonia", continent: "Europe", iso_code: "MK", flag_url: "https://flagcdn.com/mk.svg" },
  { name: "Norway", continent: "Europe", iso_code: "NO", flag_url: "https://flagcdn.com/no.svg" },
  { name: "Oman", continent: "Asia", iso_code: "OM", flag_url: "https://flagcdn.com/om.svg" },
  { name: "Pakistan", continent: "Asia", iso_code: "PK", flag_url: "https://flagcdn.com/pk.svg" },
  { name: "Palau", continent: "Oceania", iso_code: "PW", flag_url: "https://flagcdn.com/pw.svg" },
  { name: "Palestine", continent: "Asia", iso_code: "PS", flag_url: "https://flagcdn.com/ps.svg" },
  { name: "Panama", continent: "North America", iso_code: "PA", flag_url: "https://flagcdn.com/pa.svg" },
  { name: "Papua New Guinea", continent: "Oceania", iso_code: "PG", flag_url: "https://flagcdn.com/pg.svg" },
  { name: "Paraguay", continent: "South America", iso_code: "PY", flag_url: "https://flagcdn.com/py.svg" },
  { name: "Peru", continent: "South America", iso_code: "PE", flag_url: "https://flagcdn.com/pe.svg" },
  { name: "Philippines", continent: "Asia", iso_code: "PH", flag_url: "https://flagcdn.com/ph.svg" },
  { name: "Poland", continent: "Europe", iso_code: "PL", flag_url: "https://flagcdn.com/pl.svg" },
  { name: "Portugal", continent: "Europe", iso_code: "PT", flag_url: "https://flagcdn.com/pt.svg" },
  { name: "Qatar", continent: "Asia", iso_code: "QA", flag_url: "https://flagcdn.com/qa.svg" },
  { name: "Romania", continent: "Europe", iso_code: "RO", flag_url: "https://flagcdn.com/ro.svg" },
  { name: "Russia", continent: "Europe", iso_code: "RU", flag_url: "https://flagcdn.com/ru.svg" },
  { name: "Rwanda", continent: "Africa", iso_code: "RW", flag_url: "https://flagcdn.com/rw.svg" },
  { name: "Saint Kitts and Nevis", continent: "North America", iso_code: "KN", flag_url: "https://flagcdn.com/kn.svg" },
  { name: "Saint Lucia", continent: "North America", iso_code: "LC", flag_url: "https://flagcdn.com/lc.svg" },
  { name: "Saint Vincent and the Grenadines", continent: "North America", iso_code: "VC", flag_url: "https://flagcdn.com/vc.svg" },
  { name: "Samoa", continent: "Oceania", iso_code: "WS", flag_url: "https://flagcdn.com/ws.svg" },
  { name: "San Marino", continent: "Europe", iso_code: "SM", flag_url: "https://flagcdn.com/sm.svg" },
  { name: "Sao Tome and Principe", continent: "Africa", iso_code: "ST", flag_url: "https://flagcdn.com/st.svg" },
  { name: "Saudi Arabia", continent: "Asia", iso_code: "SA", flag_url: "https://flagcdn.com/sa.svg" },
  { name: "Senegal", continent: "Africa", iso_code: "SN", flag_url: "https://flagcdn.com/sn.svg" },
  { name: "Serbia", continent: "Europe", iso_code: "RS", flag_url: "https://flagcdn.com/rs.svg" },
  { name: "Seychelles", continent: "Africa", iso_code: "SC", flag_url: "https://flagcdn.com/sc.svg" },
  { name: "Sierra Leone", continent: "Africa", iso_code: "SL", flag_url: "https://flagcdn.com/sl.svg" },
  { name: "Singapore", continent: "Asia", iso_code: "SG", flag_url: "https://flagcdn.com/sg.svg" },
  { name: "Slovakia", continent: "Europe", iso_code: "SK", flag_url: "https://flagcdn.com/sk.svg" },
  { name: "Slovenia", continent: "Europe", iso_code: "SI", flag_url: "https://flagcdn.com/si.svg" },
  { name: "Solomon Islands", continent: "Oceania", iso_code: "SB", flag_url: "https://flagcdn.com/sb.svg" },
  { name: "Somalia", continent: "Africa", iso_code: "SO", flag_url: "https://flagcdn.com/so.svg" },
  { name: "South Africa", continent: "Africa", iso_code: "ZA", flag_url: "https://flagcdn.com/za.svg" },
  { name: "South Korea", continent: "Asia", iso_code: "KR", flag_url: "https://flagcdn.com/kr.svg" },
  { name: "South Sudan", continent: "Africa", iso_code: "SS", flag_url: "https://flagcdn.com/ss.svg" },
  { name: "Spain", continent: "Europe", iso_code: "ES", flag_url: "https://flagcdn.com/es.svg" },
  { name: "Sri Lanka", continent: "Asia", iso_code: "LK", flag_url: "https://flagcdn.com/lk.svg" },
  { name: "Sudan", continent: "Africa", iso_code: "SD", flag_url: "https://flagcdn.com/sd.svg" },
  { name: "Suriname", continent: "South America", iso_code: "SR", flag_url: "https://flagcdn.com/sr.svg" },
  { name: "Sweden", continent: "Europe", iso_code: "SE", flag_url: "https://flagcdn.com/se.svg" },
  { name: "Switzerland", continent: "Europe", iso_code: "CH", flag_url: "https://flagcdn.com/ch.svg" },
  { name: "Syria", continent: "Asia", iso_code: "SY", flag_url: "https://flagcdn.com/sy.svg" },
  { name: "Taiwan", continent: "Asia", iso_code: "TW", flag_url: "https://flagcdn.com/tw.svg" },
  { name: "Tajikistan", continent: "Asia", iso_code: "TJ", flag_url: "https://flagcdn.com/tj.svg" },
  { name: "Tanzania", continent: "Africa", iso_code: "TZ", flag_url: "https://flagcdn.com/tz.svg" },
  { name: "Thailand", continent: "Asia", iso_code: "TH", flag_url: "https://flagcdn.com/th.svg" },
  { name: "Timor-Leste", continent: "Asia", iso_code: "TL", flag_url: "https://flagcdn.com/tl.svg" },
  { name: "Togo", continent: "Africa", iso_code: "TG", flag_url: "https://flagcdn.com/tg.svg" },
  { name: "Tonga", continent: "Oceania", iso_code: "TO", flag_url: "https://flagcdn.com/to.svg" },
  { name: "Trinidad and Tobago", continent: "North America", iso_code: "TT", flag_url: "https://flagcdn.com/tt.svg" },
  { name: "Tunisia", continent: "Africa", iso_code: "TN", flag_url: "https://flagcdn.com/tn.svg" },
  { name: "Turkey", continent: "Asia", iso_code: "TR", flag_url: "https://flagcdn.com/tr.svg" },
  { name: "Turkmenistan", continent: "Asia", iso_code: "TM", flag_url: "https://flagcdn.com/tm.svg" },
  { name: "Tuvalu", continent: "Oceania", iso_code: "TV", flag_url: "https://flagcdn.com/tv.svg" },
  { name: "Uganda", continent: "Africa", iso_code: "UG", flag_url: "https://flagcdn.com/ug.svg" },
  { name: "Ukraine", continent: "Europe", iso_code: "UA", flag_url: "https://flagcdn.com/ua.svg" },
  { name: "United Arab Emirates", continent: "Asia", iso_code: "AE", flag_url: "https://flagcdn.com/ae.svg" },
  { name: "United Kingdom", continent: "Europe", iso_code: "GB", flag_url: "https://flagcdn.com/gb.svg" },
  { name: "United States", continent: "North America", iso_code: "US", flag_url: "https://flagcdn.com/us.svg" },
  { name: "Uruguay", continent: "South America", iso_code: "UY", flag_url: "https://flagcdn.com/uy.svg" },
  { name: "Uzbekistan", continent: "Asia", iso_code: "UZ", flag_url: "https://flagcdn.com/uz.svg" },
  { name: "Vanuatu", continent: "Oceania", iso_code: "VU", flag_url: "https://flagcdn.com/vu.svg" },
  { name: "Vatican City", continent: "Europe", iso_code: "VA", flag_url: "https://flagcdn.com/va.svg" },
  { name: "Venezuela", continent: "South America", iso_code: "VE", flag_url: "https://flagcdn.com/ve.svg" },
  { name: "Vietnam", continent: "Asia", iso_code: "VN", flag_url: "https://flagcdn.com/vn.svg" },
  { name: "Yemen", continent: "Asia", iso_code: "YE", flag_url: "https://flagcdn.com/ye.svg" },
  { name: "Zambia", continent: "Africa", iso_code: "ZM", flag_url: "https://flagcdn.com/zm.svg" },
  { name: "Zimbabwe", continent: "Africa", iso_code: "ZW", flag_url: "https://flagcdn.com/zw.svg" },
];

const seedCountries = async () => {
  try {
    console.log("Seeding countries...");
    for (const country of countries) {
      await pool.query(
        `INSERT INTO countries (name, continent, iso_code, flag_url)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (iso_code) DO NOTHING`,
        [country.name, country.continent, country.iso_code, country.flag_url]
      );
    }
    console.log(`Seeded ${countries.length} countries successfully`);
    pool.end();
  } catch (err) {
    console.error("Seed error:", err.message);
    pool.end();
  }
};

seedCountries();